cmake_minimum_required(VERSION 3.31)
set(CMAKE_PROJECT_TOP_LEVEL_INCLUDES .devcontainer/cmake/xproinc.cmake)
project(FFmpeg)
include(GNUInstallDirs)
include(xpflags)
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  string(TOLOWER ${PROJECT_NAME} prj)
  file(GLOB libs mswbin/bin/*.lib)
  file(GLOB dlls mswbin/bin/*.dll)
  install(FILES ${libs} DESTINATION ${CMAKE_INSTALL_LIBDIR})
  install(PROGRAMS ${dlls} DESTINATION ${CMAKE_INSTALL_BINDIR})
  install(DIRECTORY mswbin/include/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${prj})
endif()
